services:
  db:
    image: mysql/mysql-server:latest
    container_name: local_mysql_db
    restart: no
    environment:
      - MYSQL_ROOT_HOST=172.18.0.1
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
